name: C/C++ CI

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
           sudo apt-get update
           sudo apt-get upgrade -y
           sudo apt-get install libboost-all-dev libpng-dev libjpeg-dev libwebp-dev libc6-dev libssl-dev -y
           cmake -DCMAKE_BUILD_TYPE=release
           make -j8 arc_unpacker
