name: C/C++ CI

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
           sudo apt-get install libboost-all-dev libwebp
           cmake -DCMAKE_BUILD_TYPE=release
           make -j8
